CREATE DATABASE TPC_EQUIPO_5
GO
USE TPC_EQUIPO_5
GO

CREATE TABLE Provincias(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(80) NOT NULL
)
CREATE TABLE Ciudades(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(80) NOT NULL,
    IDProvincia INT NOT NULL FOREIGN KEY REFERENCES Provincias(ID)
)
CREATE TABLE Metodos_de_pago(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Metodo_de_pago VARCHAR(50) NOT NULL
)
CREATE TABLE Estados_Pedido(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(80) NOT NULL
)
CREATE TABLE Categorias(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(80) NOT NULL
)
CREATE TABLE Marcas(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(80) NOT NULL
)
CREATE TABLE Tipos_Imagenes(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Tipo VARCHAR(80) NOT NULL
)
CREATE TABLE Imagen(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Descripcion VARCHAR(80) NOT NULL,
    IDArticulo INT NOT NULL FOREIGN KEY REFERENCES Articulos(ID),
    Tipo_Imagen INT NOT NULL FOREIGN KEY REFERENCES Tipos_Imagenes(ID)
)
CREATE TABLE Datos_Personales(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Nombres VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Telefono INT NULL,
    Direccion VARCHAR(100),
    IDCiudad INT NULL FOREIGN KEY REFERENCES Ciudades(ID)
    --Falta foto de perfil
)
CREATE TABLE Usuarios(
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Usuario VARCHAR(50) NOT NULL, 
    Clave VARCHAR(50) NOT NULL,
    Administrar BIT NOT NULL,
    IDDatos_Personales INT FOREIGN KEY REFERENCES Datos_Personales(ID)
)

CREATE TABLE Productos()
CREATE TABLE Pedidos()


